#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * generate_production_secrets.js
 *
 * IMPORTANT: This script generates a .env.production file with clearly
 * identifiable placeholder values. Every API key is prefixed with
 * "placeholder_" so there is zero risk of confusing these with real keys.
 *
 * After running this script, you MUST replace every placeholder with
 * real credentials from your service providers.
 *
 * NEVER run this in CI or production — it is a local dev/scaffolding tool only.
 */

const fs = require('fs');
const crypto = require('crypto');

// Generate random hex tokens (safe for session secrets, encryption keys, etc.)
const sessionSecret = crypto.randomBytes(32).toString('hex');
const nextauthSecret = crypto.randomBytes(32).toString('hex');
const encryptionKey = crypto.randomBytes(32).toString('hex');
const cronSecret = crypto.randomBytes(32).toString('hex');
const videoTokenSecret = crypto.randomBytes(32).toString('hex');

// Placeholder prefixes to prevent confusion with real API keys
const PH = 'placeholder_';

const secrets = {
  // Core secrets — cryptographically random, safe to use as-is
  SESSION_SECRET: sessionSecret,
  NEXTAUTH_SECRET: nextauthSecret,
  ENCRYPTION_KEY: encryptionKey,
  CRON_SECRET: cronSecret,
  VIDEO_TOKEN_SECRET: videoTokenSecret,

  // Service API keys — clearly identifiable placeholders
  UPSTASH_REDIS_REST_TOKEN: PH + 'upstash-redis-token',
  ZENMUX_API_KEY: PH + 'zenmux-api-key',
  OPENAI_API_KEY: PH + 'openai-api-key',
  ANTHROPIC_API_KEY: PH + 'anthropic-api-key',
  RESEND_API_KEY: PH + 'resend-api-key',
  SENDGRID_API_KEY: PH + 'sendgrid-api-key',
  STRIPE_SECRET_KEY: PH + 'stripe-secret-key',
  STRIPE_WEBHOOK_SECRET: PH + 'stripe-webhook-secret',
  SENTRY_DSN: PH + 'sentry-dsn',
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: PH + 'stripe-publishable-key',
  NEXT_PUBLIC_STRIPE_PK: PH + 'stripe-publishable-key',
  NEXT_PUBLIC_SENTRY_DSN: PH + 'sentry-dsn-public',
};

const content = `# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  PRODUCTION ENVIRONMENT                                               ║
# ║  ALL VALUES MARKED WITH "placeholder_" MUST BE REPLACED              ║
# ║  BEFORE DEPLOYING TO PRODUCTION.                                     ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# ⚠ WARNING ⚠
# Values prefixed with "placeholder_" are NOT real API keys.
# They are scaffolding placeholders generated by scripts/generate_production_secrets.js.
# Attempting to use them in production WILL cause service failures.
#
# To obtain real credentials, visit each service provider's dashboard:
#   - OpenAI:     https://platform.openai.com/api-keys
#   - Stripe:     https://dashboard.stripe.com/apikeys
#   - Resend:     https://resend.com/api-keys
#   - Supabase:   https://supabase.com/dashboard/project/_/settings/api
#   - Sentry:     https://sentry.io/settings/account/api/auth-tokens/
#   - Upstash:    https://console.upstash.com/redis
#   - SendGrid:   https://app.sendgrid.com/settings/api_keys
#   - ZenMux:     https://zenmux.com/dashboard/api-keys
#   - Anthropic:  https://console.anthropic.com/account/keys
#
# NOTE: Do NOT hardcode NODE_ENV in this file. Next.js sets it automatically.

# ─── Core ─────────────────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_URL=https://kynthai.app
NEXT_PUBLIC_API_URL=https://kynthai.app/api

# ─── US Compliance ───────────────────────────────────────────────────────────
NEXT_PUBLIC_COMPLIANCE_MODE=US
NEXT_PUBLIC_JURISDICTION=Delaware, United States
NEXT_PUBLIC_PRIVACY_OFFICER_EMAIL=privacy@kynthai.app
NEXT_PUBLIC_SUPPORT_EMAIL=support@kynthai.app

# ─── Database (HIPAA: TLS required) ──────────────────────────────────────────
DATABASE_URL=postgresql://kynthai:***@db:5432/kynthai_us?schema=public&sslmode=require
DIRECT_URL=postgresql://kynthai:***@db:5432/kynthai_us?schema=public&sslmode=require
POSTGRES_USER=kynthai
POSTGRES_PASSWORD=***
POSTGRES_DB=kynthai_us

# ─── Auth / Security ─────────────────────────────────────────────────────────
NEXTAUTH_URL=https://kynthai.app
ADMIN_EMAILS=admin@kynthai.app
CORS_ORIGIN=https://kynthai.app,https://www.kynthai.app

# ─── Core Secrets (cryptographically random — safe to use as generated) ──────
SESSION_SECRET=${secrets.SESSION_SECRET}
NEXTAUTH_SECRET=${secrets.NEXTAUTH_SECRET}
ENCRYPTION_KEY=${secrets.ENCRYPTION_KEY}
CRON_SECRET=${secrets.CRON_SECRET}
VIDEO_TOKEN_SECRET=${secrets.VIDEO_TOKEN_SECRET}

# ─── Service API Keys (REPLACE ALL placeholder_ values) ──────────────────────
UPSTASH_REDIS_REST_TOKEN=${secrets.UPSTASH_REDIS_REST_TOKEN}
ZENMUX_API_KEY=${secrets.ZENMUX_API_KEY}
OPENAI_API_KEY=${secrets.OPENAI_API_KEY}
ANTHROPIC_API_KEY=${secrets.ANTHROPIC_API_KEY}
RESEND_API_KEY=${secrets.RESEND_API_KEY}
SENDGRID_API_KEY=${secrets.SENDGRID_API_KEY}
STRIPE_SECRET_KEY=${secrets.STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${secrets.STRIPE_WEBHOOK_SECRET}
SENTRY_DSN=${secrets.SENTRY_DSN}
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
NEXT_PUBLIC_STRIPE_PK=${secrets.NEXT_PUBLIC_STRIPE_PK}
NEXT_PUBLIC_SENTRY_DSN=${secrets.NEXT_PUBLIC_SENTRY_DSN}

# ─── Rate Limiting (Upstash Redis) ───────────────────────────────────────────
UPSTASH_REDIS_REST_URL=${PH}upstash-redis-rest-url

# ─── Payments ────────────────────────────────────────────────────────────────
NEXT_PUBLIC_DEFAULT_CURRENCY=USD
NEXT_PUBLIC_STRIPE_US=true

# ─── Email / Notifications ───────────────────────────────────────────────────
SENDGRID_FROM_EMAIL=noreply@kynthai.app
NEXT_PUBLIC_NOTIFICATION_PROVIDER=resend

# ─── Analytics ───────────────────────────────────────────────────────────────
NEXT_PUBLIC_MIXPANEL_TOKEN=${PH}mixpanel-token
NEXT_PUBLIC_GOOGLE_ANALYTICS=${PH}ga-measurement-id
NEXT_PUBLIC_POSTHOG_KEY=${PH}posthog-key
NEXT_PUBLIC_POSTHOG_HOST=https://us.i.posthog.com

# ─── Storage / Media ────────────────────────────────────────────────────────
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${PH}cloudinary-cloud-name
CLOUDINARY_API_KEY=${PH}cloudinary-api-key
CLOUDINARY_API_SECRET=${PH}cloudinary-api-secret
NEXT_PUBLIC_UPLOAD_PRESET=kynthai_us

# ─── Feature Flags ──────────────────────────────────────────────────────────
NEXT_PUBLIC_ENABLE_US_LAUNCH=true
NEXT_PUBLIC_ENABLE_HIPAA_MODE=true
NEXT_PUBLIC_ENABLE_CCPA_MODE=true
NEXT_PUBLIC_ENABLE_STRIPE_US=true
NEXT_PUBLIC_ENABLE_DEMO=false
`;

const outputPath = process.argv[2] || '/Users/c.k/Downloads/kynthai-restored-7000-us/.env.production';

fs.writeFileSync(outputPath, content);

console.log('');
console.log('⚠️  WARNING: This file contains PLACEHOLDER values, not real API keys.');
console.log('   Every service key is prefixed with "placeholder_".');
console.log('   Do NOT deploy this file to production without replacing them.');
console.log('');
console.log('📁 Generated: ' + outputPath);
console.log('');
console.log('🔑 Random core secrets (safe to use):');
console.log(`  SESSION_SECRET:       ${sessionSecret.substring(0, 20)}...`);
console.log(`  NEXTAUTH_SECRET:      ${nextauthSecret.substring(0, 20)}...`);
console.log(`  ENCRYPTION_KEY:       ${encryptionKey.substring(0, 20)}...`);
console.log(`  CRON_SECRET:          ${cronSecret.substring(0, 20)}...`);
console.log('');
console.log('🔒 Placeholder service keys (MUST REPLACE):');
Object.entries(secrets).forEach(([key, value]) => {
  if (String(value).startsWith('placeholder_')) {
    console.log(`  ${key}: ${value}`);
  }
});
console.log('');
console.log('✅ .env.production template generated. Replace all placeholder_ values before deploying.');
process.exit(0);
